### ISSUE TITLE
Some embedded knowledge that should be explicit

### ISSUE THREAD

**Issue by AddictArts** [icholy/git-get#1]
`git get [<options>] [--] <repo>`

`[<options>] [--]` are for git clone not git-get right?

Just wanting to understand, cheers and thanks for the tool.

**Comment by icholy** [comment]
@AddictArts yes, all the arguments are forwarded to `git clone`. Unfortunately, the `--help` flag tries too look up docs for `git get` instead of `git clone`. Not sure how to work around that.

**Comment by icholy** [comment]
@AddictArts I'm open to PRs if you want to improve the readme or `--help` issue.

**Comment by icholy** [comment]
@AddictArts I've updated the README. Let me know if you think it's sufficient.

**Comment by AddictArts** [comment]
Looks great, thanks, I’ll close this.
